site_name: InTensorfiers' Documentation
repo_url: https://github.com/InTensorfiers/intensorfiers.github.io
repo_name: InTensorfiers/intensorfiers.github.io
theme:
  name: material
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: yellow
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/meteor

nav:
  - Introduction: 'index.md'
  - 1. Introduction:
    - Overview: "introduction/overview.md"
    - Project Architecture: "introduction/project-architecture.md"
    - Toolchain:
      - Ansible: "introduction/toolchain/ansible.md"
      - Conda: "introduction/toolchain/conda.md"
  - 2. Installation:
    - Overview: "installation/installation-process-overview.md"
    - Steps:
      - Operating System(OS): "installation/steps/install-os.md"
      - GPU drivers: "installation/steps/install-gpu.drivers.md"
      - Miniconda: "installation/steps/Installing Miniconda.md"
      - CUDA: "installation/steps/install-cuda.md"
      - Dependencies: "installation/steps/install-dependencies.md"
    - Ansible Playbook: "installation/Playbook.md"
  - 3. Benchmarks:
    - Overview: "benchmarks/overview.md"
extra_css:
  - stylesheets/extra.css